# Generated by Django 4.1 on 2023-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imagenew_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenew',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
