# Generated by Django 4.1 on 2023-06-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_predresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='classification',
        ),
    ]
